baseURL = 'https://ayynash.net'
languageCode = 'en-us'
title = 'Nash Gibson'

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

[params]
  sitename = 'Nash Gibson'
  defaultColor = 'dark'
  description = ':p'

[params.author]
  name = 'Nash Gibson'
  intro = 'HALLO :D'
  description = 'Welcome to my site! all my socials and useful links live here.'

[params.logo]
  path = "/images/logo.png"
  alt = "Nash Gibson logo"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/nashknoxgibson-dev"

[[params.socialIcons]]
  name = "instagram"
  url = "https://instagram.com/ayenash"

[[params.socialIcons]]
  name = "x"
  url = "https://x.com/notaynash"

[[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/@AyyNash727"

[[params.socialIcons]]
  name = "discord"
  url = "https://discord.gg/ayynash"

[outputs]
  home = ['HTML']
  section = ['HTML']
  taxonomy = ['HTML']
  term = ['HTML']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  identifier = "members"
  name = "Members"
  url = "/members/"
  weight = 20